INSERT INTO rus_binomen (genus, species, rus_genus, rus_species) VALUES
('Stipa',  'pennata', 'Ковыль', 'перистый'),
('Potentilla', 'recta', 'Лапчатка', 'прямая'),
('Rhodiola', 'rosea', 'Родиола', 'розовая'),
('Astragalus', 'permiensis', 'Астрагал', 'пермский'),
('Nymphoides', 'supina', 'Болоцветник', 'щитолистный'),
('Asperula', 'petreaea', 'Ясменник', 'скальный'),
('Sanicula', 'uralensis', 'Подлесник', 'уральский'),
('Anemone', 'uralensis', 'Ветреница', 'уральская'),
('Pulsatilla', 'ambigua', 'Прострел', 'сомнительный'),
('Androsace', 'maxima', 'Проломник', 'большой'),
('Oxytropus', 'uralensis', 'Остролодочник', 'уральский'),
('Anemone', 'dichotoma', 'Ветреница', 'вильчатая'),
('Rhodiola', 'quadrifida', 'Родиола', 'четырёхраздельная'),
('Centaurea', 'integrifolia', 'Василёк', 'цельнолистный'),
('Calluna', 'vulgaris', 'Вереск', 'обыкновенный'),
('Glycyrrhiza', 'uralensis', 'Солодка', 'уральская'),
('Gypsophila', 'uralensis', 'Качим', 'уральский');